name: 'helm-cicd-toolkit'
description: 'configures a kubernetes toolkit for your actions => Includes: kubectl, helm, helm-docs, ct, jq, yq'
branding:
  icon: 'terminal'
  color: 'blue'
inputs:
  kubectl_version:
    description: 'kubectl version, e.g. `v1.21.0`'
    required: false
    default: "1.27.0"
  helm_version:
    description: 'helm cli version, e.g. `v3.7.0`'
    required: false
    default: "3.11.3"
  helm_docs_version:
    description: 'helm-docs version'
    required: false
    default: '1.11.0'
  yq_version:
    description: 'yq version'
    required: false
    default: '4.33.3'
  ct_version:
    description: 'ct version'
    required: false
    default: '3.8.0'
runs:
  using: "composite"
  steps:
    - shell: bash
      run: |
        echo "using kubectl@${{ inputs.kubectl_version }}"
        sudo wget -q "https://dl.k8s.io/release/v${{ inputs.kubectl_version }}/bin/linux/amd64/kubectl" -O /usr/local/bin/kubectl \
            && sudo chmod +x /usr/local/bin/kubectl


        echo "using helm@${{ inputs.helm_version }}"
        sudo wget -q https://get.helm.sh/helm-v${{ inputs.helm_version }}-linux-amd64.tar.gz -O - | tar -xzO linux-amd64/helm > /usr/local/bin/helm


        echo "using helm-docs@${{ inputs.helm_docs_version }}"
        sudo wget -q https://github.com/norwoodj/helm-docs/releases/download/v${{ inputs.helm_docs_version }}/helm-docs_${{ inputs.helm_docs_version }}_Linux_x86_64.tar.gz -O - | tar -xzO helm-docs > /usr/local/bin/helm-docs


        echo "using yq@${{ inputs.yq_version }}"
        sudo wget -q https://github.com/mikefarah/yq/releases/download/v${{ inputs.yq_version }}/yq_linux_amd64 -O /usr/local/bin/yq \
            && sudo chmod +x /usr/local/bin/yq

        echo "using ct@$ct_version"
        sudo wget -q https://github.com/helm/chart-testing/releases/download/v${{ inputs.ct_version }}/chart-testing_${{ inputs.ct_version }}_linux_amd64.tar.gz -O - | tar -xzO ct > /usr/local/bin/ct \
            && sudo chmod +x /usr/local/bin/ct


